### ISSUE TITLE
Allow embedding a single issue

### ISSUE THREAD

**Issue by yoiang** [Frostplexx/obsidian-github-issues#14]
Hello! The plugin feels like a great start! To use it more strategically it would be lovely to be able to specify individual issues rather than having to see and search through all issues in a repo.

Something along the lines of ...

```
Frostplexx/obsidian-github-issues#1
```

...where `#1` is the issue perhaps?

**Comment by frostplexx** [comment]
This sounds like a great idea! But I think issue #9 should be solved first, as this sounds like an exact use case where you would want to be able to embed multiple issues per file.

**Comment by frostplexx** [comment]
You can now embed selected issues using the following notation
```
Frostplexx/obsidian-github-issues#1
Frostplexx/obsidian-github-issues#1-10
Frostplexx/obsidian-github-issues#1,2,3,4,5
Frostplexx/obsidian-github-issues#1-10,11,23,100
```

**Comment by JanRau** [comment]
Great! This should be added to the usage section in the readme file
