### ISSUE TITLE
Plugin interface will disappear sometimes

### ISSUE THREAD

**Issue by yoiang** [Frostplexx/obsidian-github-issues#15]
Hello! I haven't figured out a step by step reproduction yet, I apologize.

Sometimes after finishing editing the plugin block the entire block will fully disappear where I would expect some sort of result or placeholder, even if an operation is pending. Otherwise it looks like I broke something, or the block was deleted somehow. The only way to find it again is to scroll the text carat up or down into the block's edit mode again, which can be difficult on a busy page.

**Comment by frostplexx** [comment]
I don't seem to be able to replicate this bug. Does it occur after you manually edit the code block or while e.g. interacting with the issue details? Are you using any custom themes?
