### ISSUE TITLE
I am excited for this plugin!

### ISSUE THREAD

**Issue by noklam** [Frostplexx/obsidian-github-issues#16]
I just made a post here https://forum.obsidian.md/t/obsidian-github-issues-pr-integration-not-using-github-to-sync/65334, then I find this repository.

I saw there is a plan to support bi-direction sync. What will be the workflow of it? I am interested to know more what's the motivation for you to create this plugin and how are you going to use it?

For me I really want to have my own issue trackers, so I intend to use Obsidian as my local mini clone of Github Issue/PR + my personal notes. At time I can add more tags and link issues properly.

**Comment by frostplexx** [comment]
From what I read in your forum post you want to be able to reference GitHub issues in other notes and have your issues synced (offline) to your Obsidian Vault? This plugin is more meant as a way to interact with your GitHub issues without leaving Obsidian. Some example scenarios I thought about while making this plugin are:

- You have a project Dashboard or somethings along those lines where you can see your issues among other things related to your project and you can organise everything in one place (e.g. comment on issues, close them,...)
- You embed single issues and then under (or above) it you take notes on how you could for example solve it.

This plugin, at the moment at least, also doesn't work offline as it fetches all its information for the GitHub api.
