### ISSUE TITLE
Main JS is missing from the release 

### ISSUE THREAD

**Issue by g1ronn1mo** [Frostplexx/obsidian-github-issues#17]
I tryed to install the plugin via [BRAT](https://notes.nicolevanderhoeven.com/Obsidian42+BRAT+plugin).

When copy pasting `Frostplexx/obsidian-github-issues` into the installation field and hit `Add plugin, I get this issue:

`BRAT:
The release is not complete and cannot be downloaded. main.js is missing from the release`

Mzybe this can be changed while BRAT is a good way to keep the beta plugins updated.

**Comment by frostplexx** [comment]
Fixed by adding a manifest-beta.json with the correct release number inside.
