### ISSUE TITLE
GitHub Enterprise support

### ISSUE THREAD

**Issue by rpuncel** [Frostplexx/obsidian-github-issues#18]
In order to use this with GitHub Enterprise, there will need to at least be a plugin setting for specifying an API endpoint.  I think the default could be github.com.

I think the initial take on this could require that a vault only uses one GitHub instance, but there is a use case for folks that do some work on public GitHub and some work on GitHub Enterprise to be able to combine both in their Obsidian Notes.

**Comment by rpuncel** [comment]
Note: I'd be happy to learn how to contribute this feature, but I did not see a CONTRIBUTING.md, so please let me know if you have any thoughts or guidelines.

**Comment by frostplexx** [comment]
Thanks for the feature request! Yeah this project doesn't have any real documentation because I didn't expect it to get any traction at all, so I'd say just fork it and open a PR with your changes.

**Comment by frostplexx** [comment]
You can now specify a custom endpoint
