### ISSUE TITLE
Add example usage to README

### ISSUE THREAD

**Issue by rpuncel** [Frostplexx/obsidian-github-issues#19]
To understand the syntax of the plugin, I needed to crack open the main.ts from the release archive I downloaded, especially to find how to specify a repository for a note.

Perhaps this is because the interface is still in work, but something small like this example being added to the README would be helpful:
````
```github-issues
Frostplexx/obsidian-github-issues
```
````

**Comment by JanRau** [comment]
Is there a way to specify not only the repository but a specific issue within this repository? So one note and note issue? 

Update: Nevermind, this question is answered here: https://github.com/frostplexx/obsidian-github-issues/issues/14
