### ISSUE TITLE
Installation problems 

### ISSUE THREAD

**Issue by JanRau** [Frostplexx/obsidian-github-issues#23]
I hope I am not missing something completely obvious, but the installation as outlined in the read.me doesn't seem to work for me. 

- I am downloading Source code (zip) file from https://github.com/frostplexx/obsidian-github-issues/releases
- I copy paste the file to path/vault_name\.obsidian\plugins
- I am using 7zip and "Extract files here" to unzip the folder
- In Obsidian -> Options -> Community Plugins "GitHub Issues" does show up after refreshing, but does not offer an "Option" button and cannot be activated
- The error message is "Failed to load plugin "obsidian-github-issues"

![Picture2](https://github.com/frostplexx/obsidian-github-issues/assets/69148007/8e76ec34-ffee-46f3-b3cf-2e41043a56f7)

**Comment by obtips** [comment]
You could just delete all files in the folder "obsidian-github-issues", then only download and move 3 files(main.js, manifest.json, styles.css) into it, then try it again.

**Comment by JanRau** [comment]
Thank you! The folder doesn't seem to contain a main.js file, though? Only main.ts and main.yml in subfolders?

**Comment by obtips** [comment]
> Thank you! The folder doesn't seem to contain a main.js file, though? Only main.ts and main.yml in subfolders?

download them here.
https://github.com/frostplexx/obsidian-github-issues/releases/tag/0.3.1

**Comment by JanRau** [comment]
Ahh, thank you! That worked!
